workflows:
  dispatch.yml:
    title: Austen's Workflow
    description: This is a test
    inputs:
      string_input:
        label: Branch
        description: Pick a branch
        placeholder: Austen's placeholder
        type: select
        optionsFrom:
          source: branches
      number_input:
        description: Number input (numeric value)
      boolean_input:
        description: Boolean input (true/false toggle)
      choice_input:
        description: Choice input (select from predefined options)
        placeholder: asdasd
      environment_input:
        description: Environment input (select from repository environments)
        validationMessage: Invalid environment input
    groups:
      - title: Group 1
        inputs:
          - boolean_input
          - environment_input
      - title: Group 2
        inputs:
          - number_input
          - choice_input
