workflows:
  dispatch.yml:
    title: Dispatch
    description: Describe your workflow here 123
    inputs:
      string_input:
        description: String input (free-form text)
      number_input:
        description: Number input (numeric value)
      boolean_input:
        description: Boolean input (true/false toggle)
      choice_input:
        description: Choice input (select from predefined options)
        placeholder: asdasd
      environment_input:
        description: Environment input (select from repository environments)
        validationMessage: Invalid environment input
