name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  who-to-greet:
    description: 'Who to greet'
    default: 'Mona the Octocat'
    required: false

outputs:
  greeting:
    description: 'The greeting message'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}