name: Call (CoM/MEDDPICC)
description: Open an issue for a GitHub demo, Q&A or technical call that is aligned with the CoM & MEDDPICC process.
title: "Call: replace_with_company_name, replace_with_date yyyy-MMM-dd"
labels: ["activity-call"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Demo issue!
  - type: input
    id: company_name
    attributes:
      label: Company
      description: Company Name
    validations:
      required: false
  - type: input
    id: salesforce_link
    attributes:
      label: Salesforce
      description: Link to SFDC records
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Meeting brief and Agenda
      description: Fill here the meeting brief and agenda. What is the sales cycle/account goal that this call helps to fulfill? What is the expected role/need for the SE on the call?
    validations:
      required: false
  - type: input
    id: opportunity_size
    attributes:
      label: "Potential opportunity size"
  - type: textarea
    id: participants
    attributes:
      label: Participants 
      description: "Participants, job titles and locations (if known):"
    validations:
      required: false
  - type: dropdown
    id: products
    attributes:
      label: Current SCM
      description: Current version control tools in use - _**mark all applicable**_.
      multiple: true
      options:
        - GHEC (GitHub Enterprise Cloud)
        - GHES (GitHub Enterprise Server)
        - GitHub Teams
        - GitHub Legacy
        - GitLab (Cloud or Server)
        - BitBucket (Cloud or Server)
        - Azure DevOps (Cloud or Server)
        - AWS CodeCommit
        - Non-Git (TFS, Subversion, Mercurial, Perforce, etc)
        - No SCM
        - Other
    validations:
      required: false
  - type: input
    id: scm_other
    attributes:
      label: "SCM (other)"
  - type: input
    id: integrations
    attributes:
      label: "Third party integrations"
  - type: markdown
    attributes:
      value: |
        # Customer's interest in GitHub today
  - type: textarea
    id: pains
    attributes:
      label: Current State & Identified Pain
      description: Current pain points / frustrations / challenges - **Business** and **Technical**.
    validations:
      required: false
  - type: textarea
    id: outcomes
    attributes:
      label: Desired Future State / Business Outcomes
      description: How do they want things to work in the future? What are the positive business outcomes if they acheive these goals?  What challenges do they have to overcome to achieve these goals? E.g. Improve collaboration and reduce friction by having a single VCS, promote Innersource and code reuse, reduce developer's onboarding time, better secure the software they ship etc.
    validations:
      required: false
  
  - type: textarea
    id: capabilities
    attributes:
      label: Required Capabilities
      description: What are the 2/3 things that we need to show them Github can help with (demo's are always better when we show them ways we can solve the problems they have today)
    validations:
      required: false
 
  
  - type: textarea
    id: decisions
    attributes:
      label: Decision criteria
      description: What are the key criteria / 'must have's' they are using to determine which solution they will choose?
    validations:
      required: false
  - type: textarea
    id: challenges
    attributes:
      label: Challenges/Blockers
      description: Any blockers/challenges/competitors, that will make it harder for GH to close the oppotunity (i.e. 3rd Party tools they are using (e.g. JIRA, Artifactory, Jenkins), competitors they are assessing along side GH, or internal challenges such as budget pressures?
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional info that will make your SE best prepared to support you on this deal.
    validations:
      required: false

# thoughts:
# - meddpicc
# - decision making criteria
# - metrics
# - value drivers? accelerate production of high wuality software developement and delivery, securing the software we ship, improving organizational efficiency
# - pain points
# - desired outcomes
# - challenges, or do you have any gaps in qualification that we can help fill?
# - what's the opportunity background? deal size? general status? known qualification gaps?
# - what are  business and technical pains? size of pain? who is impacted, how do you know?
# - what are the positive business outcomes? who cares about the outcomes? how are they tied to the company's top business initiatives
# - if we were to win this deal why would we win? what's our deal strategy moving forward?
