name: Actions Usage Alert

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
env:
  ORG: octodemo
  GITHUB_TOKEN: ${{ secrets.AUSTEN_PAT }}
  TOTAL_MINS_USED_ALERT_THRESHOLD: 50000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actions-billing=$(gh api /orgs/$ORG/settings/billing/actions)" >> "$GITHUB_OUTPUT"
        id: api
      - if: fromJson(steps.api.outputs.actions-billing).total_minutes_used >= env.TOTAL_MINS_USED_ALERT_THRESHOLD
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'CHANNEL_ID,ANOTHER_CHANNEL_ID'
          slack-message: "The total minutes used by the Actions in the $ORG organization has exceeded the threshold of $TOTAL_MINS_USED_ALERT_THRESHOLD. The current total minutes used is ${{fromJson(steps.api.outputs.actions-billing).total_minutes_used}}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}