name: Artifacts Reusable Called

on:
  workflow_call:

jobs:
  download-and-print:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: my-artifact
      - run: cat my_file.txt