name: Bicep Params from Vars

on: workflow_dispatch

jobs:
  bicep_params:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bicep parameters file
        env:
          VARS: ${{ toJSON(vars) }}
        run: |
          echo "$VARS" | jq -r 'to_entries[] | "param \(.key) string = \"\(.value)\""' >> params.bicep
      - run: cat params.bicep
      - uses: actions/upload-artifact@v4
        with:
          name: params
          path: params.bicep
      # - run: az deployment group create --resource-group <resource-group-name> --template-file <path-to-bicep> --parameters @params.bicep
  
  # Only use variables that start with "BICEP_"
  bicep_params_2:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bicep parameters file
        env:
          VARS: ${{ toJSON(vars) }}
        run: |
          echo "$VARS" | jq -r 'to_entries[] | select(.key | startswith("BICEP_")) | "param \(.key) string = \"\(.value)\""' >> params.bicep