on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: austenstone/actions-playground/.github/actions/composite-action@main
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
