name: Container Custom Home

on: workflow_dispatch

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1 -e HOME=/mycustomhome
    steps:
      - run: 'echo HOME=/home/sf | tee -a $GITHUB_ENV'
      - run: echo $HOME