on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from a workflow!"
      - run: gh pr comment ${{ github.event.pull_request.number }} --body "Hello from a workflow!"
        env:
          GH_TOKEN: ${{ github.token }}