on:
  label:
    types: [created, deleted]
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        required: true
        default: '1.0'
  push:
  pull_request:
    branches:
      - main

jobs:
  run1:
    strategy:
      matrix:
        foo: ['1.0', '2.0', '3.0']
    runs-on: ubuntu-latest
    steps:
      - run: echo "The version is ${{ matrix.foo }}"

  deploy:
    needs: run1
    environment:
      name: production
      url: 'http://localhost'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from a ${{ vars.NAME }}!"
      - run: echo "Hello from a ${{ secrets.SUPER_SECRET }}!"
    timeout-minutes: 10