on:
  label:
    types: [created, deleted]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Merge')
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from a workflow!"
      - uses: austenstone/list-repository-languages@main
        id: list-languages
      - run: gh pr comment ${{ github.event.pull_request.number }} --body "It's been labeled"
        env:
          GH_TOKEN: ${{ github.token }}