on:
  label:
    types: [created, deleted]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from a workflow!"

  run2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from a workflow!"