on:
  label:
    types: [created, deleted]
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        required: true
        default: '1.0'
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.foo }} > foo.txt
      - uses: actions/upload-artifact@v4
        with:
          path: foo.txt
          name: foo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo
      - run: ls -al
      - run: cat foo.txt
      - run: echo ${{ github.event.inputs.foo }} >> foo.txt
      - run: cat foo.txt