on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze User Activity
        id: analyze_user_activity
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.AUSTEN_PAT }}
          organization: octodemo
          activity_days: 90
      
      - name: Save User Activity Report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_user_activity.outputs.report_csv }}
