name: Dynamic Envs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - id: build-env
        run: echo "envs=['env1', 'env2', 'env3']" >> "$GITHUB_OUTPUT"
    outputs:
      env-names: ${{ steps.build-env.outputs.envs }}

  print:
    runs-on: ubuntu-latest
    needs: [build-env]
    strategy:
      matrix:
        name: ${{ fromJson(needs.build-env.outputs.env-names) }}
      fail-fast: false
    steps:
      - run: echo "Hello ${{ matrix.name }}!"
