name: Expressions1

on: workflow_dispatch

jobs:
  determine_files_changed:
    runs-on: ubuntu-latest
    outputs:
      build_protected: ${{ steps.step1.outputs.build_protected }}
    steps:
      - id: step1
        run: echo "build_protected=true" >> "$GITHUB_OUTPUT"
  build_alpha_tconnect:
      needs: determine_files_changed
      uses: ./.github/workflows/reusable-called.yml
      with:
        username: ${{ needs.determine_files_changed.outputs.build_protected == 'true' }}
      secrets: inherit
