name: Expressions1

on: workflow_dispatch

jobs:
  determine_files_changed:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=true" >> "$GITHUB_OUTPUT"
  determine_files_changed_print:
    needs: determine_files_changed
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.determine_files_changed.outputs.test }}
  build_alpha_tconnect:
      needs: determine_files_changed
      uses: ./.github/workflows/reusable-called.yml
      with:
        username: ${{ needs.determine_files_changed.outputs.test == 'true' }}
      secrets: inherit
