name: GitHub App Packages
on:
  workflow_dispatch:
  push:
jobs:
  get-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: austenstone
          repositories: workflow-dispatch-sync
      - env:
          NPM_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "@${OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
      - run: npm install @austenstone/workflow-dispatch-sync@1.1.0