name: GitHub App Checkout
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: austenstone
      REPOS: private
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ ENV.OWNER }}
          repositories: ${{ env.REPOS }}
      - uses: actions/checkout@v3
        with:
          repository: private
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - run: cat README.md