name: Google Survey

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          body: |
            please fill out 👉 [this survey](https://docs.google.com/forms/d/1Hz5E1X3PeSGWjSlz7ER8cJ5HkWKG-uagyrmnALCSdHM/prefill) 👈
