name: Matrix

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  print:
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    run: echo $fruit $animal $color $shape

# will result in six jobs with the following matrix combinations:
# {fruit: apple, animal: cat, color: pink, shape: circle}
# {fruit: apple, animal: dog, color: green, shape: circle}
# {fruit: pear, animal: cat, color: pink}
# {fruit: pear, animal: dog, color: green}
# {fruit: banana}
# {fruit: banana, animal: cat}