name: Matrix Outputs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: ['linux', 'windows','macos']
        arch: ['x86','x64']
    steps:
      - id: step1
        run: echo "result_${{ matrix.os }}_${{ matrix.arch }}=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.result }}
      - run: echo ${{ toJson(needs.job1.outputs) }}
      - run: echo ${{ toJson(needs.job1) }}
