name: Matrix Outputs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      result: ${{ toJson(steps.step1.outputs) }}
    strategy:
      fail-fast: false
      matrix:
        os: ['linux', 'windows','macos']
    steps:
      - id: step1
        run: |
          RANDOM_NUMBER=$((RANDOM))
          RANDOM_STRING=$(openssl rand -hex 12)
          echo "${{ matrix.os }}_random_number=$RANDOM_NUMBER" >> "$GITHUB_OUTPUT"
          echo "${{ matrix.os }}_random_string=$RANDOM_STRING" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{ fromJson(needs.job1.outputs) }}"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/github-script@v4
      with:
        script: |
          console.log(process.env.result)
      env:
        result: ${{ fromJson(needs.job1.outputs) }}
