# Merge pull request when label is added
name: Basic

# On pull request labeled
on:
  pull_request:
    branches: [ "main" ]
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'Merge' ||
      github.event.label.name == 'merge'
    steps:
      - uses: actions/checkout@v3
      - run: gh pr merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.AUSTEN_PAT }}