name: Only during working hours

on:
  workflow_dispatch:

jobs:
  is-work-hour:
    outputs:
      is-work-hour: ${{ steps.is-work-hour.outputs.is-work-hour }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: is-work-hour
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const date = new Date();
          const day = date.getDay();
          const hour = date.getHours();
          const isWorkHour = day > 0 && day < 6 && hour > 8 && hour < 18;
          return {
            'is-work-hour': isWorkHour
          };
  build:
    runs-on: ubuntu-latest
    needs: is-work-hour
    if: needs.is-work-hour.outputs.is-work-hour == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.