name: Only during working hours

on:
  workflow_dispatch:

jobs:
  is-work-hour:
    outputs:
      is-work-hour: ${{ steps.is-work-hour.outputs.is-work-hour }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: is-work-hour
      env:
        WORKING_HOUR_START: 12
        WORKING_HOUR_END: 18
        WORKING_WEEK_START: 1
        WORKING_WEEK_END: 5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const date = new Date();
          const day = date.getDay();
          const hour = date.getHours();
          const isWorkHour = day >= parseInt(process.env.WORKING_WEEK_START) &&
            day <= parseInt(process.env.WORKING_WEEK_END) &&
            hour >= parseInt(process.env.WORKING_HOUR_START) &&
            hour <= parseInt(process.env.WORKING_HOUR_END);
          return {
            'is-work-hour': isWorkHour
          };
    - run: exit 1
      if: steps.is-work-hour.outputs.is-work-hour != 'true'
  build:
    runs-on: ubuntu-latest
    needs: is-work-hour
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.