name: Recursive Reusable Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        default: ${{ github.actor }}
        required: false
        type: string

jobs:
  recurse:
    uses: ./.github/workflows/recursion-reusable-called.yml
    with:
      username: ${{ github.actor + ',' + inputs.username }}
      
