name: Find and Replace

on: workflow_dispatch

jobs:
  find-and-replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
            SHA: ${{ github.sha }}
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('test.json');

            const json = JSON.parse(content);
            const parts = json.monitoredResourceId.split('/');
            parts[1] = process.env.SHA;
            parts.join('/');
            json.monitoredResourceId = parts;

            fs.writeFileSync('test.json', JSON.stringify(json));
