name: Basic
run-name: This was run by @${{ github.actor }} with message ${{ github.event.head_commit.message }}
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo Hello World
