name: Container Service - Redis
on:
  push:

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      
    steps:
      - run: apt-get install -y telnet
      - run: telnet nginx 80
