name: Service Containers

on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      
    steps:
      - run: sudo apt-get update && sudo apt-get install -y telnet
      - run: telnet nginx 80
