name: Container Service - Redis
on:
  push:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node

    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      
    steps:
      - run: npx detect-port 80 --verbose
