name: Basic
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: exit 1
      - uses: austenstone/.github/.github/actions/notify-slack-action@main
        if: always()
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}