name: Stats
on: workflow_dispatch
jobs:
  stats:
   runs-on: ubuntu-latest
   steps:
   - uses: runforesight/workflow-telemetry-action@v1
   - run: echo hello world
   - run: sudo apt-get install stress
   - run: stress
